version: '3.8'

services:
  app:
    build: ./app_service
    ports:
      - "8000:8000"
    volumes:
      - ./data/chroma:/app/data/chroma
      - ./models:/app/models
    depends_on:
      - chromadb
      - llm

  chromadb:
    build: ./vector_db
    ports:
      - "8001:8000"
    volumes:
      - ./data/chroma:/data/chroma

  llm:
    build: ./llm_service
    ports:
      - "8002:8001"
    volumes:
      - ./models/llm:/models